# Generated by Django 4.1 on 2025-01-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not specified', 'Not specified')], default='N', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Student_class', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=15, null=True)),
                ('section', models.CharField(blank=True, max_length=15, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_img/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='student.parents')),
            ],
        ),
    ]
