# Generated by Django 4.1 on 2025-01-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
