# Generated by Django 4.1 on 2025-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_date_created_userprofile_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('IsSystemAdmin', 'IsSystemAdmin'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=30, null=True),
        ),
    ]
