# Generated by Django 4.1 on 2025-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('IsSystemAdmin', 'IsSystemAdmin'), ('General User', 'General User'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=30, null=True),
        ),
    ]
